### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by ghost**
- [x] Banner
- [x] Page 0 (title)
- [x] Page 1 (flying to Komona)
- [x] Page 2 (convincing Saffron)
- [x] Page 3 (confronting the godmothers)
- [x] Page 4 (the godmothers' plan)
- [x] Page 5 (seeing the monster)
- [x] Page 6 (the attack and the lesson)
- [x] Page 7 (patrons)
- [ ] Maybe invent a better title

@Willem3141

### CODE REVIEW

**Comment by Willem3141** [comment]
Thanks for doing the translation; I see that I'm too late again :grinning: 

I'll proofread tomorrow (I'm not at my laptop now, so I can't open SVG files...)

**Comment by ghost** [comment]
I've just made some improvements and adapted the layout of the speech bubbles to match the translation.
Please be bold and say what you think can be improved, @Willem3141!

**Comment by Willem3141** [comment]
@M1dgard I read your translation, it is very nice :smile: I made only a few changes:
- Page 2: ‘praten met hen’ changed into ‘met ze praten’
- Page 3: ‘alléén’ changed into ‘in je eentje’
- Page 3: ‘geen in de hekserij’ changed into ‘dan niet in de hekserij’. This could also be rendered as ‘geen lesje in de hekserij’, but dropping ‘lesje’ feels strange. (To me at least...)
- Page 4: ‘niet meer van de jongste’: removed ‘van’
- Page 5: ‘ingesteldheid’ sounds really weird to me; I prefer ‘instelling’. I never heard this before, so I looked it up and it seems this is a Netherlands / Flanders difference. If you don't like ‘instelling’, we could rephrase to something like ‘Prachtig! Zo mag ik het zien!’

Do you agree with those?

As for the episode title... I think this one is fine, actually. Maybe it is a bit long, but in any case, I cannot come up with a ‘catchier’ one.

Thanks for the translation work!

**Comment by ghost** [comment]
> I read your translation, it is very nice :smile:

Thanks :smile: 

> Page 2: ‘praten met hen’ changed into ‘met ze praten’

Would you agree to change it to "met hen praten"? "ze" is for subjects (nominative) while "hen" is for objects (LV, subjunctive). The difference is fading in contemporary language use but I'm a bit conservative... :p

> Page 3: ‘alléén’ changed into ‘in je eentje’

Sounds equally fluent if not more fluent to my Flemish ear. :)

> Page 3: ‘geen in de hekserij’ changed into ‘dan niet in de hekserij’. This could also be rendered as ‘geen lesje in de hekserij’, but dropping ‘lesje’ feels strange. (To me at least...)

Indeed, it's better like this.

> Page 4: ‘niet meer van de jongste’: removed ‘van’

Must be another flemisism. It sounds a little bit less fluent like this, but it is acceptable. Alternatives include "We worden er (ook) niet jonger op", "We worden al een dagje ouder", "We zijn (al) niet meer zo jong". What do we do?

> Page 5: ‘ingesteldheid’ sounds really weird to me; I prefer ‘instelling’. I never heard this before, so I looked it up and it seems this is a Netherlands / Flanders difference. If you don't like ‘instelling’, we could rephrase to something like ‘Prachtig! Zo mag ik het zien!’

Seems like we really have a language difference here. I can't shake off the feeling that "Dat is de goede instelling" means "That's the right institute", not even within the given context. We'll have to go with your other suggestion.

Thank you for your corrections!

**Comment by ghost** [comment]
> > @Willem3141 said: Page 5: ‘ingesteldheid’ sounds really weird to me; I prefer ‘instelling’. I never heard this before, so I looked it up and it seems this is a Netherlands / Flanders difference. If you don't like ‘instelling’, we could rephrase to something like ‘Prachtig! Zo mag ik het zien!’
> 
> @M1dgard said: Seems like we really have a language difference here. I can't shake off the feeling that "Dat is de goede instelling" means "That's the right institute", not even within the given context. We'll have to go with your other suggestion.

What do you think of "Zo mag ik het horen?" instead of "zien"? Is that a common idiom in the Netherlands?

**Comment by ghost** [comment]
Great :)
I think we're done then?

**Comment by Willem3141** [comment]
I made it ‘met hen praten’, ‘we worden al een dagje ouder’, and ‘zo mag ik het horen’. This all sounds fine to me :smile:

> I think we're done then?

Yes, I think we can push to master.

**Comment by ghost** [comment]
Ok, merging in 3, 2, 1 ...

**Comment by Willem3141** [comment]
Uhm... I already merged it :fearful:

**Comment by ghost** [comment]
No problem! Now it looks like we're working together. I'll remove the branch then. :stuck_out_tongue:

**Comment by Willem3141** [comment]
Heh :wink: Thanks again and have a good night!

**Comment by Deevad** [comment]
A big big thank you to you both!

**Pull request merged**
