### PR TITLE
Danish translation

### PR DESCRIPTION
**Pull request by emmilinette**
With @Alkarex

### CODE REVIEW

**Comment by Alkarex** [comment]
@Deevad Nous n'avons pas trouvé comment ajouter un peu de marge à la première ligne pour que le *å* ne soit pas coupé. Cela marche en ajoutant une ligne blanche avant, mais c'est perdu à la ré-ouverture. Augmenter la hauteur de ligne ne change rien pour la première ligne :
image

**Comment by Deevad** [comment]
@Alkarex  Thank you for the PR :+1: 

Ha true it's known issue in Inkscape. I'm not sure how I can solve this. I'll tend to accuse the font a bit too ; "Lavi" because this special characters were added by me and maybe they need additional setup. But I made a quick test and I could also reproduce bug with more common accents. I promise I'll tweak it. ;-)

**Comment by Deevad** [comment]
screenshot from 2017-11-05 19-27-29

I think I found the culprit: the Lavi font itself. I'll fix and push it.

**Comment by Deevad** [comment]
Fixed in https://github.com/Deevad/peppercarrot_fonts/commit/91a3aa32dc3a15f8110ff3d4add7e448c0d6d4a5 , Now let's re-render again :)

**Comment by Alkarex** [comment]
Great!
Link to the results https://www.peppercarrot.com/da/article369/episode-16-the-sage-of-the-mountain
So far, the *å* are still cut, but I am not sure whether it is before or after the re-rendering :-)
image
image

**Comment by Deevad** [comment]
@Alkarex : The rendering took time because I'm stupid, and I updated the da_* files ; but I forgot to feed the renderfarm with the updated Lavi.ttf font. Now it's done :) Thank you for double-checking. https://www.peppercarrot.com/da/article369/episode-16-the-sage-of-the-mountain

**Pull request merged**
